services:
  uploader:
    build: ./uploader
    command: >
      kintone-plugin-uploader
      --base-url ${KINTONE_BASE_URL}
      --username ${KINTONE_USERNAME}
      --password ${KINTONE_PASSWORD}
      plugin.zip
    volumes:
      - ./plugin.zip:/workspace/plugin.zip:ro
    cap_add:
      - SYS_ADMIN
